### ISSUE TITLE
Hebergement - Exploration

### ISSUE THREAD

**Issue by abouillon-ets** [Monitoring-Mtl/Serverless-API#10]
Il faudrait etre en mesure de rendre l'acces a notre API publique avec jettons. Cela dit, il faudra explorer sur quelles plateformes nous allons deployer notre application et quel domaine nous allons utiliser pour acceder a celle-ci ?

A verifier avec les professeurs a cet effet.

**Comment by pabdelli** [comment]
Nous utiliseront pour commencer l'addresse fournis par le service AWS. Si on doit utiliser un domaine, la décision sera prise subséquement. Un compte AWS sera fournis par les mainteneurs du projet. Nous utilisons aussi un environnement de developpement AWS fournis par Mathieu (chargé de cour ETS).
