### ISSUE TITLE
API Documentation Tool Exploration (Swagger, OpenAPI, etc)

### ISSUE THREAD

**Issue by abouillon-ets** [Monitoring-Mtl/Serverless-API#11]
Use cases / user stories
Ouvrir l’application – Choisir un arrêt de bus – Consulter :
Les prochains bus qui arrêteront
Leur capacité / occupation
Des possibles alertes de retard / autres
Ouvrir l’application – Choisir un trajet – Consulter :
Les différents arrêts sur la ligne
Le temps d’arrivée estimé de chaque arrêt
Ouvrir l’application – sur la page principale
Signaler s’il y a une ou plusieurs disruptions de service
Voir les trajets affectés, et les impacts sur ceux-ci
Si un user a des trajets ou arrêts en « favoris », il aura les alertes seulement pour ces arrêts spécifiques
Idées de endpoints
/bus/{id}/locations. GET (avoir la position temps réel des bus)
/bus/routes GET (avoir les infos des routes des bus)
/route/{id} GET
/route/{id}/stops GET (avoir les infos des localisations des arrêts)
/stops GET
/stops/{id} GET
/bus/occupancy GET (avoir les infos sur l’occupation du bus en temps réel)
/service/alerts. GET (s’il y a des arrêts de services ou délai, pour les m-a-j)
/service/alerts/{id}. GET
/analyse/buses/alertes POST Body qui contient les informations d’une route, d’un autobus et d’une alertes
/analyse/routes/alertes POST analyse des impacts d’une alertes (incident) sur une route

**Comment by pabdelli** [comment]
La premiere iteration du Swagger est deployer. Le premiers endpoints sont mis a jour avec leurs informations. Il faudra creer de nouvelles issues pour les endpoints plus specifiques a l'analyse et a ce que le F-E aura besoin.
