### ISSUE TITLE
Clean Up - Organize

### ISSUE THREAD

**Issue by abouillon-ets** [Monitoring-Mtl/Serverless-API#13]
Il serait important de nettoyer le projet template, organiser un structure de fichier, et s'assurer que les tous les documents de configurations portent les bon noms, etc.

**Comment by SimonSt-Pierre** [comment]
- Template pour les PR
- Template pour les bugs
- Template pour les features
- Template pour la documentation

**Comment by SimonSt-Pierre** [comment]
- Created templates for PR, bugs, features and docs.
- They are added to the .github directory
- To be visible to github, they are added in folders named ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE

**Comment by SimonSt-Pierre** [comment]
I believe the templates need to be pushed on MAIN in order to test the functionality.
