### ISSUE TITLE
Contacter superviseurs afin d'obtenir un compte AWS

### ISSUE THREAD

**Issue by abouillon-ets** [Monitoring-Mtl/Serverless-API#14]
Afin de pouvoir commencer à déployer nos services, il est nécessaire d'obtenir les accès d'un compte AWS qui sera utilisé pour gérer toutes les ressources cloud reliées au projet. Pour cela, il faut entrer en communication rapidement avec les superviseurs pour qu'ils puissent créer un compte AWS et nous partager les identifiants.

**Comment by abouillon-ets** [comment]
@pabdelli A écrit à Francis via Teams. Ils ont eu un appel concernant la possibilité d'obtenir un compte AWS.
@jeremy a aussi un appel avec Francis. Voici un résumé de leur discussion :

Si aws est pas responsive présentement c'est parce que qqn est malade, il va revenir plus tard vers nous
Si aws veut envoyer des crédits à l'ETS, on pourra créer le compte aws et mettre logo sur la vitrine

**Comment by abouillon-ets** [comment]
@pabdelli a eu un contact pour des informations sur le déploiement serverless, nous avons obtenu un compte AWS Academy pour nous quatre et avec 100$ de crédit grâce à Mathieu Dupuis (chargé de cours à l'ÉTS). Nous n'avons pas besoin d'avoir une carte de crédit et les services arrêtent si jamais nous atteignons 100$.

EDIT : Le compte limite beaucoup les acces necessaires pour deployer nos infrastructure. Nous avons de la difficulte a tester car beaucoup de features sont bloques....

**Comment by pabdelli** [comment]
Apres discussion avec Julien, le compte partager personnel de Julien pour "hoster" les services AWS ne conviendra pas. Se compte ne permet pas de partager des acces ce qui force Julien a accepter chaques connection avec un 2FA. Cela ralentir terriblement le developpement, et n'est pas une option viable.

Nous explorons la possibilite de creer un compte "organization" qui supportera le projet.
