### ISSUE TITLE
Create Tests - Spike

### ISSUE THREAD

**Issue by pabdelli** [Monitoring-Mtl/Serverless-API#20]
Reflechir au framework de choix pour les tests ?

**Comment by SimonSt-Pierre** [comment]
* Lire sur le mocking AWS + exemples :
  * https://www.npmjs.com/package/aws-sdk-mock
* Tester la DynamoDB? (mocks)
* UNIT TESTS : Error handling, vérifier le data envoyé dans Lambda
* Tester la pipeline CI/CD ?
