### ISSUE TITLE
Ajouter Linter dans le pipeline

### ISSUE THREAD

**Issue by pabdelli** [Monitoring-Mtl/Serverless-API#21]
Ajouter la verification et l'éxécution du linter ESLint ( & prettier ? ) lors d'une pull request

**Comment by lamiphil** [comment]
Recherche ChatGPT :
5. Auto-Fixing:

One of the powerful features of ESLint is its ability to automatically fix certain types of issues. By using the --fix flag when running ESLint, it will attempt to auto-correct any fixable problems.

Dans la pipeline, il va probablement être nécessaire d'exécuter la commande d'exécution de ESLint avec le flag --fix afin que le code soit réparer avant d'être merged sur la main branch.

**Comment by lamiphil** [comment]
Le linting est fait automatiquement mais les changements ne sont pas apportés et commit lors de la PR. Je vais devoir continuer à debugger.
