### ISSUE TITLE
Rapport de coverage Jest

### ISSUE THREAD

**Issue by pabdelli** [Monitoring-Mtl/Serverless-API#32]
Il faudra automatiser l'execution de Jest dans le pipeline et generer le rapport Jest (HTML), ce HTML devrait etre automatiquement deployer sur une page GitHub Pages.

**Comment by SimonSt-Pierre** [comment]
Liens intéressants pour un starting point :
- https://medium.com/@serverlessinc/unit-testing-for-node-js-serverless-projects-with-jest-bd8476dd41ec
- https://stackoverflow.com/questions/64738154/testing-aws-severless-application-using-jest
Documentation d'Amazon :
- https://docs.aws.amazon.com/lambda/latest/dg/typescript-testing.html

**Comment by pabdelli** [comment]
https://dev.to/mbarzeev/auto-publish-your-test-coverage-report-on-github-pages-35be

Exactemetn ca, ca dlair ben facile.

**Comment by lamiphil** [comment]
Close on commit duplicate of https://github.com/Monitoring-Mtl/Serverless-API/issues/33
