### ISSUE TITLE
Automatisation du Rapport Jest - Pipeline

### ISSUE THREAD

**Issue by pabdelli** [Monitoring-Mtl/Serverless-API#33]
Voir issue : https://github.com/orgs/Monitoring-Mtl/projects/1/views/2?pane=issue&itemId=40640579

**Comment by lamiphil** [comment]
This issue was a duplicate of issue : https://github.com/orgs/Monitoring-Mtl/projects/1/views/1?pane=issue&itemId=40527344
Closing this issue because the original was closed.
