### ISSUE TITLE
Convertir Lambda Function python pour TS

### ISSUE THREAD

**Issue by abouillon-ets** [Monitoring-Mtl/Serverless-API#38]
On veut convertir le script python qui fetch et enregistre les données pour le format TS une fois le projet converti de JS à TS.

**Comment by pabdelli** [comment]
On pense creer un projet en python car les librairies pour la manipulation de donnees semble plus facile dans ce language. Nous aurons donc un nouveau projet de plusieurs (micro-services) ou plutot Lambda functions, qui rouleront en python pour faire l'insertion et le nettoyage des donnees dynamiques
