### ISSUE TITLE
Revoir la structures des tables DynamoDB Et la structure des données

### ISSUE THREAD

**Issue by abouillon-ets** [Monitoring-Mtl/Serverless-API#40]

**Comment by abouillon-ets** [comment]
Revoir la structure des données pour réduire la taille de chaque item (250 Bytes).
Revoir le format de la tables.
Ingérer les données directement dans S3 + BatchWrite dans DynamoDB pour le live Data (STM_live_data) et (STM_Historique) par exemple.

**Comment by abouillon-ets** [comment]
Le nombre de véhicules augmente considérablement durant la semaine. (Entre 500 et 700 véhicules). J'ai effectué plusieurs tests avec des tables DynamoDB. Environ 16-19 secondes pour l'exécution de la fonction Lambda

**Comment by abouillon-ets** [comment]
DynamoDB n'est pas viable pour la taille des données, plus de 1000 véhicules dans les heures de pointes. La fonction Lambda prend 30secondes ++ à s'exécuter et le "free tier" du 25 Write Unit dépasse ou n'est pas suffisant. 

Athena qui est utilisé pour exécuter des queries à partir de bucket S3 n'est pas gratuit non plus. Le coût est en fonction du nombre de requête ET de la taille de l'objet qui est query. (On va devoir diminuer la taille des fichiers et voir le nombre de requêtes effectués,)

**Comment by pabdelli** [comment]
En reference avec l'analyse dynamoDB, nous tenterons une version qui utilisera seulement un bucket S3 et Athena pour Query les donnees filtres !
