### ISSUE TITLE
SPIKE - Data Lake - vehiclePosition history

### ISSUE THREAD

**Issue by pabdelli** [Monitoring-Mtl/Serverless-API#43]
On aimerait conserver un historique a moyen  / long terme, des déplacements des autobus à des fins d'analyse. Cela devra passer par le stockage de masse des données et ensuite par des moyens de filtration, nettoyage. 

AWS - Glue
AWS - S3
AWS - Athena 
... autres ?

**Comment by pabdelli** [comment]
@abouillon-ets Cette issue est pas mal complété ?

**Comment by abouillon-ets** [comment]
On récupère les données 'Vehicle Positions' toutes les X secondes et les conservons dans un bucket S3 selon la structure de répertoire 'Bucket/YYYY/MM/DD/files.parquet'. Nous utilisons également une fonction Lambda pour l'agrégation de ces données afin d'obtenir un seul fichier contenant toutes les données 'Vehicle Positions' de la journée pour les autobus. Ce fichier est un '.parquet' et a une taille d'environ 40MB pour une journée de semaine, avec des données mises à jour toutes les 12 secondes (5 fois par minute).
