### ISSUE TITLE
AWS Lambda

### ISSUE THREAD

**Issue by abouillon-ets** [Monitoring-Mtl/Serverless-API#7]
Approfondir les connaissances et lancer une premiere iteration AWS Lambda pour aller "fetch" les donnees a partir d'un API de la ville, de maniere automatique et synchroniser (5 minutes).

**Comment by pabdelli** [comment]
L'architecture préconisé par  la personne ressource que nous avons contacté est un server NodeJS avec Express wrapper avec une librairie serverless qui permet de lancer le serveur node a chaque appel du endpoint pour lancer la fonction Lambda. Nous avons donc décidé d'utiliser cette approche et de faire un projet complet de serveur API NodeJS Express Serverless
