### ISSUE TITLE
Creation du Mono repo pour les Micro-services Python

### ISSUE THREAD

**Issue by pabdelli** [Monitoring-Mtl/Serverless-API#73]
## Feature Request

**Description:**

On veut creer un nouveau repo pour heberger et deployer les micro-services qui seront en python et utiliseront du serverless Lambda

**Use Case:**

Pour toutes les collections et insertions / analyse des donnees dynamiques

**Proposed Solution:**

If you have any ideas on how this feature could be implemented, please describe them here.

**Alternative Solutions:**

Aucune pour l'instant

**Additional Information:**

## Checklist

- [x] I have searched for existing feature requests that are similar.
- [x] I have provided a clear and concise description of the feature.
- [x] I have explained the use case for the feature.
- [x] I have considered possible implementation approaches.

**Comment by abouillon-ets** [comment]
Nouveau repo est créer.
