### ISSUE TITLE
Transferer fonction de scrapping dans le nouveau projet

### ISSUE THREAD

**Issue by pabdelli** [Monitoring-Mtl/Serverless-API#74]
## Feature Request

**Description:**

Transferer la fonction qui roule dans un environnement de test dans le repo principal 

**Use Case:**

Scrapper pour aller chercher les donnees dynamiques de la STM

**Proposed Solution:**

Lambda function Python

**Alternative Solutions:**

Autres languages

**Additional Information:**

## Checklist

- [ ] I have searched for existing feature requests that are similar.
- [ ] I have provided a clear and concise description of the feature.
- [ ] I have explained the use case for the feature.
- [ ] I have considered possible implementation approaches.

**Comment by abouillon-ets** [comment]
Avec 60 secondes, on obtient beaucoup d'arrêt qui ne sont pas pris en compte. J'ai ajusté à 20 secondes le fetch avec le service "StepFunction" qui permet de lancer la lambda function à toute les 20 secondes. Par contre, il y a un coût monétaire non négligable avec ce services. Je test dans l'environnement de DEV (compte AWS Infrastructure donné par Mathieu Dupuis avec 100$ de crédit) pour évaluer le coût d'un mois.

**Comment by abouillon-ets** [comment]
Finalement la Step Functions que j'avais utilisé n'était pas une "Express" qui est beaucoup moins chère, mais est limité à 5 minutes maximum de up time (dans notre cas on la run à chaque minute, donc pas un problème). 
Le coût est calculé par "Workflow requests" par mois, étant donné qu'on effectue 3 request dans StepFunction (3 fois l'appel de la Lambda en 1 minute) ça donne environ 133920 requests / month -> avec une durée moyenne de 1500ms et de 128MB de mémoire. Ça donne 0.55$ pour fetch à toute les 20 secondes pour la STM. 

Round up by 64 MB (128) = 128 MB of memory consumed by each workflow
MB of memory consumed by each workflow rounded to 64 MB chunks: 128
Round up by 100 milliseconds (1500) = 1500 total duration (milliseconds)
Duration rounded up to nearest 100 milliseconds: 1,500
133,920 workflow requests x 0.001 seconds x 1,500 milliseconds = 200,880.00 seconds of execution
200,880.00 seconds of execution x 128 MB of memory consumed by each workflow = 25,712,640.00 MB-seconds
25,712,640.00 MB-seconds / 1024 GB = 25,110.00 GB-seconds
133,920 workflow requests x 0.000001 USD = 0.13 USD for monthly request charges
Monthly request charges: 0.13 USD
Tiered price for: 25,110.00 GB-seconds
25,110 GB-seconds x 0.00001667 USD = 0.42 USD
Total tier cost = 0.42 USD for monthly duration charges
Monthly duration charges: 0.42 USD
0.13 USD (monthly request charges) + 0.42 USD (monthly duration charges) = 0.55 total monthly charges
Express Workflows pricing (monthly): 0.55 USD

**Comment by abouillon-ets** [comment]
Solution peu coûteuse avec "Step Function Express". Le transfert se fera dans la prochaine itération.
