### ISSUE TITLE
Fonction Transform Data - Python

### ISSUE THREAD

**Issue by pabdelli** [Monitoring-Mtl/Serverless-API#75]
## Feature Request

**Description:**

Comme deuxieme micro-services, nous aimerions deployer une fonction de nettoyage en Python sur Lambda pour nettoyer les donnees scrapper par le premier micro-service

**Use Case:**

Voir documentation fournis par le professeur. 3 use case seront a faire

**Proposed Solution:**

Rouler un micro-service (fonction lambda) qui aggregera les donnees dynamiques recueillis et en fera l'analyse

**Alternative Solutions:**

Na

**Additional Information:**

Na

## Checklist

- [x] I have searched for existing feature requests that are similar.
- [x] I have provided a clear and concise description of the feature.
- [x] I have explained the use case for the feature.
- [x] I have considered possible implementation approaches.

**Comment by abouillon-ets** [comment]
Avec une journée test : 2023-11-15 j'obtient -> 512 612 sur 681 141 avec des données, donc 168 529 stop_times qui n'ont pas de données. 
Beaucoup de lecture et de vérification à savoir pourquoi. J'avais initialement un problème en allant récupérer mes fichiers dans le bucket S3, il y avait une limite de 1000 items lors de la récupération. Je croyais avoir un problème avec mon code pour traiter. 

Actuellement il y a des "stop_times" où il possède l'information pour calculer le delta (différence de temps entre prévu et réel), mais ne le calcul pas.
