### ISSUE TITLE
Ajuster YAML Linting

### ISSUE THREAD

**Issue by pabdelli** [Monitoring-Mtl/Serverless-API#76]
## Bug Report

**Description:**

Le linting yaml ne fonctionne pas correctement

**Steps to Reproduce:**

1. Na

**Expected Behavior:**

Improper linting

**Actual Behavior:**

Le linting des fichiers yaml devrait etre executer proprement

**Screenshots:**

If applicable, add screenshots.

**Additional Information:**

Any extra context or information about the bug.

## Checklist

- [x] I have searched for similar issues.
- [ ] I have provided clear and concise details.
- [ ] I have included steps to reproduce the bug.
- [x] I have added relevant labels (if applicable).

**Comment by lamiphil** [comment]
Closing with close of related issue : https://github.com/Monitoring-Mtl/Serverless-API/issues/48
