### ISSUE TITLE
AWS DynamoDB

### ISSUE THREAD

**Issue by abouillon-ets** [Monitoring-Mtl/Serverless-API#8]
Premier setup de la BD AWS Dynamo et ajouter les premieres donnees provenant de l'automatisation AWS Lambda

**Comment by abouillon-ets** [comment]
Lire pour importer par batch des données, au lieu de fichier par fichier.

**Comment by abouillon-ets** [comment]
J'ai créé une lambda function pour récupérer les données du GTFS du STM et les stocker directement dans DynamoDB. J'ai également créer un EventBridge qui lance la fonction toute les 60 secondes. Le but est de vérifier le volume de données que les demandes génèrent.

**Comment by abouillon-ets** [comment]
On parle de 46Gb de données pour le STM avec un "fetch" à toute les 60 secondes. la taille d'un élément (donc les données pour une autobus) est de 250 Bytes.

**Comment by abouillon-ets** [comment]
Discussion avec Mathieu Dupuis sur la façon de gérer les données, combinaison de S3 + DynamoDB.
Revoir la structure des données pour réduire la taille de chaque item (250 Bytes).
Revoir le format de la tables. 
Ingérer les données directement dans S3 + BatchWrite dans DynamoDB pour le live Data (STM_live_data) et (STM_Historique) par exemple.

**Comment by pabdelli** [comment]
Apres analyse, on tenteras une version avec simplement Athena et S3 avec des microservices qui rouleront des querys.
